name: Build App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npx electron-builder

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/
