name: Build App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run dist

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/
